scrap_app/views.py
import datetime
import json
import logging
import os

import numpy as np
import requests
from bs4 import BeautifulSoup
from flask import render_template, jsonify, request, flash, Blueprint
from flask_cors import cross_origin
from flask_login import login_required
from flask_security import roles_accepted
from keras.engine.saving import load_model
from werkzeug.utils import secure_filename

from app import app, db, allowed_file
from classification import predict_multiple_class_scrap, f1
from config import TEST_FOLDER, TEST_FOLDER_MIX, TEST_FOLDER_CLOG, test_image, TEST_FOLDER_SNOW, test_image_mix, \
    test_image_clog, test_image_snow, TEST_UPLOAD, ROOT_DIR, TEST_IMAGE_SERVER_FOLDER
from scrap_app.forms import TrainForm, TrainFormAnalysis
from scrap_app.models import Train, Statistic, ScrapLayer
from segmentation import get_multiple_segmentation, get_multiple_segmentation_mix, get_multiple_segmentation_class

test_image_checkbox = [os.path.join(TEST_FOLDER, i) for i in test_image]

test_image_mix = [os.path.join(TEST_FOLDER_MIX, i) for i in test_image_mix]
test_image_clog = [os.path.join(TEST_FOLDER_CLOG, i) for i in test_image_clog]
test_image_snow = [os.path.join(TEST_FOLDER_SNOW, i) for i in test_image_snow]

# CONFIG
scrap = Blueprint('scrap', __name__, template_folder='templates')


@scrap.route('/scrap_main')
def home():
    # title = 'Система классификации покупного лома с помощью промышленного фото анализа и машинного обучения'
    title = 'Система классификации покупного лома'
    return render_template('scrap_template/scrap.html', title=title)


# АPI ДЛЯ МЕТАЛЛОЛОМА
@scrap.route('/_get_sender/')
def _get_senders():
    number = request.args.get('number', '01', type=int)
    res = Train.query.filter_by(number=number)
    senders = [(row.id, row.sender) for row in res.distinct(Train.sender).all()]
    rails = [(row.id, row.number_rail) for row in res.distinct(Train.number_rail).all()]
    dates = [(row.id, row.date) for row in res.distinct(Train.date).all()]
    return jsonify([senders, rails, dates])


@scrap.route('/post_info_scrap', methods=["POST"])
def post_info_scrap():
    if request.method == 'POST':
        number = request.form.get('number', type=int)
        sender = request.form.get('sender', type=str)
        number_rail = request.form.get('number_rail', type=int)
        weight = request.form.get('weight', type=int)
        train = Train(
            number=number,
            sender=sender,
            date=datetime.datetime.now().date(),
            number_rail=number_rail,
            weight=weight)
        db.session.add(train)
        db.session.commit()
        return jsonify(id=train.id)


headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '3600',
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'
}
import urllib.request


def create_dir(path_1, path_2):
    import os
    path_1_full = os.path.join(TEST_IMAGE_SERVER_FOLDER, path_1)
    path_2_full = os.path.join(TEST_IMAGE_SERVER_FOLDER, path_1, path_2)
    if not os.path.exists(path_1_full):
        os.makedirs(path_1_full)
    if not os.path.exists(path_2_full):
        os.makedirs(path_2_full)
    return path_2_full


def download_create_img(url, path):
    req = requests.get(url, headers)
    soup = BeautifulSoup(req.content, 'html.parser')
    res = soup.find_all("a")
    for r in res:
        href_name = r.get('href')
        if ('jpg' or 'png') in href_name:
            href = '{}/{}'.format(url, href_name)
            urllib.request.urlretrieve(href, os.path.join(path, href_name))
            logging.info(href + ' ' + path)


@scrap.route('/post_json_scrap', methods=["POST"])
@cross_origin()
def post_json_scrap():
    if request.method == 'POST':
        url = request.form.get('url', type=str)
        path_split = os.path.split(url)
        path_2 = path_split[-1]
        path_1 = os.path.split(path_split[0])[-1]
        path = create_dir(path_1, path_2)
        logging.info('Create dirs')
        download_create_img(url, path)
        logging.info('dowload_img')
        train_id = int(path_2)
        chose_image = [os.path.split(i)[-1] for i in os.listdir(path) if 'out' not in i and 'crop' not in i]

        batch_images = get_multiple_segmentation(chose_image, os.path.join(path),
                                                 app.config['MODELS_SEGMENTATION'], is_test=False, test_folder=path)
        crop_files = [os.path.join(ROOT_DIR, i[-1]) for i in batch_images]
        model = load_model(app.config['CLASS_MODEL'], custom_objects={'f1': f1})
        result = predict_multiple_class_scrap(crop_files, model)
        # Нужно найти id c train в Statistic и обновить таблицу
        # train = Train.query.filter_by(train_id=train_id).first()
        # print(train)
        statistic = Statistic(car_id=train_id,
                              date_add=datetime.datetime.now(),
                              count_layers=len(chose_image),
                              pred_proba_layers=[float(i) for i in result[1]])
        db.session.add(statistic)
        for index, im in enumerate(batch_images):
            scrap_layer = ScrapLayer.query.filter_by(orig_pic=im[0]).first()
            if scrap_layer:
                scrap_layer.mask_pic = im[1]
                scrap_layer.crop_pic = [2]
                scrap_layer.pred_class = int(np.argmax(result[0][index])),
                scrap_layer.pred_proba = [float(i) for i in result[0][index]],
                scrap_layer.car_id = train_id

            else:
                scrap_layer = ScrapLayer(orig_pic=im[0],
                                         mask_pic=im[1],
                                         crop_pic=[2],
                                         pred_class=int(np.argmax(result[0][index])),
                                         pred_proba=[float(i) for i in result[0][index]],
                                         car_id=train_id)
            db.session.add(scrap_layer)
        db.session.commit()
        return jsonify(id=statistic.id)


@scrap.route('/post_class_scrap', methods=["POST"])
def get_class_scrap():
    if request.method == 'POST':
        file = request.files['file']
        if file.filename == '':
            resp = jsonify({'message': 'No file selected for uploading'})
            resp.status_code = 400
            return resp
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            path_file = os.path.join(app.config['TEST_UPLOAD'], filename)
            file.save(os.path.join(app.config['TEST_IMAGE_FOLDER_UPLOAD'], filename))
            print(os.path.join(app.config['TEST_IMAGE_FOLDER_UPLOAD'], filename))
            chose_image = [filename]
            batch_images = get_multiple_segmentation(chose_image, app.config['TEST_IMAGE_FOLDER_UPLOAD'],
                                                     app.config['MODELS_SEGMENTATION'], is_test=False,
                                                     test_folder=app.config['TEST_UPLOAD'])
            crop_files = [os.path.join(ROOT_DIR, i[-1]) for i in batch_images]
            model = load_model(app.config['CLASS_MODEL'], custom_objects={'f1': f1})
            # TODO: Добавить в базу данных предсказанья
            # TODO: Добавить обработку если есть фотография уже в static, то не добавлять в бд.

            result = predict_multiple_class_scrap(crop_files, model)

            graphs_av_3d = [dict(class_pred=cls, prediction=int(res)) for cls, res in
                            zip(app.config['CLASSES'], result[1])]
            return jsonify(result=graphs_av_3d, class_pred=app.config['CLASSES'][result[2][0]])


@scrap.route('/post_segment_clog', methods=["GET", "POST"])
def get_segment_clog():
    if request.method == 'POST':
        option = request.form.get('option', type=int)
        file = request.files['file']
        if file.filename == '':
            resp = jsonify({'message': 'No file selected for uploading'})
            resp.status_code = 400
            return resp
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            path_file = os.path.join(app.config['TEST_UPLOAD'], filename)
            file.save(os.path.join(app.config['TEST_IMAGE_FOLDER'], filename))
            chose_image = [filename]
            options_model = [app.config['MODELS_SEGMENTATION_MIX'], app.config['MODELS_SEGMENTATION_CLOG'],
                             app.config['MODELS_SEGMENTATION_SNOW']]
            options_dir = [app.config['TEST_IMAGE_FOLDER_UPLOAD'], app.config['TEST_IMAGE_FOLDER_UPLOAD'],
                           app.config['TEST_IMAGE_FOLDER_UPLOAD']]
            option_static = [TEST_UPLOAD, TEST_UPLOAD, TEST_UPLOAD]
            out, batch_images = get_multiple_segmentation_mix(chose_image, options_dir[option - 1],
                                                              options_model[option - 1], is_test=True,
                                                              test_folder=option_static[option - 1])
        graphs_3d = [[dict(country=int(cls), visits=int(res)) for cls, res in zip(*i)] for i in
                     out]
        mean = list(map(lambda x: sum(x) / len(x), zip(*list(zip(*out))[1])))
        # [dict(country=cls, visits=int(res)) for cls, res in zip(app.config['CLASSES'], result[1])]
        graphs_average_3d = [dict(class_pred=cls + 1, pred=int(res)) for cls, res in enumerate(mean)]

        return jsonify(graphs_average_3d)


# ОКОНЧАНИЕ API

@scrap.route('/segmentation_image', methods=["GET", "POST"])
@login_required
@roles_accepted('admin', 'scrap')
def segmentation_image():
    title = 'Сегментация металлолома'
    if request.method == 'POST':
        batch_images = request.form.getlist('image[]')
        chose_image = [os.path.split(i)[-1] for i in batch_images]

templates/scrap_template/classification_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center text-center" style="background: #373737;">
            <div class="col-sm-4 mt-4 mb-4">
                <img id="crop" src="{{ images[0][2] }}">
            </div>
            <div class="col-sm-3 justify-content-center text-center list-group m-4"
                 style="float:left; max-height: 250px; overflow: auto; display: inline-block">
                {% for image in images %}
                    <button type="button"
                            style="color: rgba(255, 255, 255, 0.4); background: #464646; outline-color: #646464;"
                            id={{ loop.index }} class="list-group-item mb-1 list-group-item-action">
                    {{ image[0].split('\\')[-1] }}
                    </button>
                {% endfor %}
            </div>
        </div>
        <div class=" row justify-content-center text-center mt-5">
            <div id="chart_one" class="column"></div>
            <div id="chart_av" class="column"></div>
        </div>
        <div>
            <div id="plot_av"></div>
        </div>
        {#TODO: перреписать генерацию графиков можно просто передвать json и все будет гуд!#}
        <!-- Chart code -->
        <script>
            var grahp_av = {{ graphJSONAverage3d | safe}};
            create_plot_pred("chart_av", grahp_av,
                "Предсказание для всех слоев металлолома",
                "Классы металлолома",
                "Процентное соотношение классов %",
                "%"
            );

            var graphs3d = {{ graphJSON3d | safe }};
            var images_result = {{images | safe}};
            create_plot_pred("chart_one", graphs3d[0],
                "Предсказание для всех слоев металлолома",
                "Классы металлолома",
                "Процентное соотношение классов %",
                "%"
            );

            var id = 1
            $('#' + id).css('color', 'rgb(255,255,255,0.64)');
            $("button").click(function () {
                if (id !== this.id) {
                    $('#' + this.id).css("color", "rgb(255,255,255,0.64)")
                    $('#' + id).css('color', 'rgba(255, 255, 255, 0.4)');
                    id = this.id;
                }
                $("#crop").attr("src", images_result[this.id - 1][2]);
                create_plot_pred("chart_one", graphs3d[this.id - 1],
                    "Предсказание для одного слоя металлолома",
                    "Классы металлолома",
                    "Процентное соотношение классов %",
                    "%"
                );
            });
        </script>
    </div>

    <style>

        .column {
            float: left;
            width: 50%;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        #chart_one, #chart_av {
            height: 500px;
        }
    </style>
{% endblock %}

templates/scrap_template/classification_upload.html
{% extends "base.html" %}


{% block content %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet prefetch" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet prefetch" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert" role="alert" id="success-alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="justify-content-center text-center">
            <form action="/classification_image" method="POST" id="CheckBox">
                <input name="train_id" value={{ train_id }}  type="number" style="display: none">
                <div class="row justify-content-center text-center" style="">
                    {% for image in images_test %}
                        <div class="col-xs-4 col-sm-3 col-md-2  m-3 nopad text-center">
                            <label class="image-checkbox">
                                <img class="img-responsive" src={{ image }}>
                                <input name="image[]" value={{ image }} type="checkbox">
                                <i class="fa fa-check hidden"></i>
                            </label>
                        </div>
                    {% endfor %}
                    <div class="progress mt-5" style="height: 28px; width: 500px">
                        <div id="dynamic" class="progress-bar bg-warning progress-bar-striped progress-bar-animated" role="progressbar" style="width: 1%"
                             aria-valuenow="1"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>

                <button type="submit" name="submit_button" id="subId" value="sub" class="btn btn-warning btn-lg m-5"
                        style="width: 414px;height: 104.74px;">
                    Классифицировать
                </button>
            </form>
        </div>
    </div>



    {#<div class="container">#}
    {#    <div class="row justify-content-center text-center">#}
    {#        <form action="/classification_image" method="POST" enctype="multipart/form-data">#}
    {#            <div class="form-group p-5"#}
    {#                 style="border: 6px dashed #FFCF24; width: 1000px; max-height: 368px; box-sizing: border-box;">#}
    {#                <div class="justify-content-center text-center">#}
    {#                    <img src="/static/css/icon%20download.svg" id="upfile" style="cursor:pointer" width="8%"#}
    {#                         max-height="8%"/>#}
    {#                    <button class="font-load" name="submit_button" id="test_images" value="test_images">Загрузить#}
    {#                        изображение#}
    {#                    </button>#}
    {#                    <!--<img src="/static/css/icon%20download.svg" id="upfile" style="cursor:pointer" width="10%" max-height="10%"/>-->#}
    {#                    <input type="file" name="files[]" multiple id="files_image" style="display: none">#}
    {#                </div>#}
    {#                <div class="progress mt-5" style="height: 28px">#}
    {#                    <div id="dynamic" class="progress-bar bg-warning" role="progressbar" style="width: 1%"#}
    {#                         aria-valuenow="0"#}
    {#                         aria-valuemin="0" aria-valuemax="100"></div>#}
    {#                </div>#}
    {#            </div>#}
    {#            <div>#}
    {#                <button type="submit" name="submit_button" value="sub" class="btn btn-warning btn-lg m-5" style="width: 414px;height: 104.74px;">#}
    {#                    Классифицировать#}
    {#                </button>#}
    {#            </div>#}
    {#        </form>#}
    {#    </div>#}
    {#</div>#}


    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="application/javascript">
        var id = {{ train_id | safe }}
        $("#upfile").click(function () {
            $("#files_image").trigger('click');
        });
        $("button").click(function () {

            $("#CheckBox").submit(function () {
                $("#subId").attr("disabled", true);
                return true;
            });
            var current_progress = 0;
            if (this.value == 'sub') {
                var filename = $('[name="image[]"]:checked').length;
                {#var filename = document.getElementById('files_image').files.length#}
            }
            //TODO: поправить передать с бека количество изображений из папки.
            if (this.value == 'test_images') {
                var filename = 10
            }
            var interval = setInterval(function () {
                current_progress += 70 / (filename * 2);
                $("#dynamic").css("width", current_progress + '%')
                if (current_progress >= 100)
                    clearInterval(interval);
            }, 1000);
            // or alert($(this).attr('id'));
        });

    </script>
    <style>

    </style>
    {#<style>#}
    {#    .font-load {#}
    {#        background: none;#}
    {#        border: none;#}
    {#        margin: 0;#}
    {#        padding: 0;#}
    {#        cursor: pointer;#}
    {#        font-family: PF Bague Sans Pro;#}
    {#        font-style: normal;#}
    {#        color: rgba(255, 255, 255, 0.4);#}
    {#        font-size: 25px;#}
    {#        line-height: 55px;#}
    {#    }#}
    {#</style>#}
{% endblock %}

templates/scrap_template/clog_list.html
{% extends "base.html" %}


{% block content %}
    <div class="container">
        <div class="row justify-content-center text-center" style="background: #373737;">
            <div class="col-sm-4 mt-4 mb-4">
                <img id="crop" src="{{ images[0][1] }}">
            </div>
            <div class="col-sm-3 justify-content-center text-center list-group m-4"
                 style="float:left; max-height: 250px; overflow: auto; display: inline-block">
                {% for image in images %}
                    <button type="button"
                            style="color: rgba(255, 255, 255, 0.4); background: #464646; outline-color: #646464;"
                            id={{ loop.index }} class="list-group-item mb-1 list-group-item-action">
                    {{ image[0].split('\\')[-1] }}
                    </button>
                {% endfor %}
            </div>
        </div>
        <div class=" row justify-content-center text-center mt-5">
            <div id="chart_one" class="column"></div>
            <div id="chart_av" class="column"></div>
        </div>
        <div>
            <div id="plot_av"></div>
        </div>
        {#TODO: перреписать генерацию графиков можно просто передвать json и все будет гуд!#}
        <!-- Chart code -->
        <script>
            var grahp_av = {{ graphJSONAverage3d | safe}};
            create_plot_pred("chart_av", grahp_av,
                "Предсказание для всех слоев металлолома",
                "Классы металлолома",
                "Процентное соотношение классов %",
                "%"
            );

            var graphs3d = {{ graphJSON3d | safe }};
            var images_result = {{images | safe}};
            create_plot_pred("chart_one", graphs3d[0],
                "Предсказание для всех слоев металлолома",
                "Классы металлолома",
                "Процентное соотношение классов %",
                "%"
            );

            var id = 1
            $('#' + id).css('color', 'rgb(255,255,255,0.64)');
            $("button").click(function () {
                if (id !== this.id) {
                    $('#' + this.id).css("color", "rgb(255,255,255,0.64)")
                    $('#' + id).css('color', 'rgba(255, 255, 255, 0.4)');
                    id = this.id;
                }
                $("#crop").attr("src", images_result[this.id - 1][1]);
                create_plot_pred("chart_one", graphs3d[this.id - 1],
                    "Предсказание для одного слоя металлолома",
                    "Классы металлолома",
                    "Процентное соотношение классов %",
                    "%"
                );
            });

        </script>
    </div>

    <style>

        .column {
            float: left;
            width: 50%;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        #chart_one, #chart_av {
            height: 500px;
        }
    </style>
{% endblock %}

templates/scrap_template/scrap_analytic.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

        {# содержимое приложения которое должно быть предоставлено в блоке app_content #}
        {% block app_content %}{% endblock %}
    </div>
    <div class="container">
        <form class="form form-horizontal" method="post" role="form">
            <div class="row">
                <div class="col">
                    {{ wtf.form_field(form.number_train) }}
                </div>
                <div class="col">
                    {{ wtf.form_field(form.sender) }}
                </div>
                <div class="col">
                    {{ wtf.form_field(form.number_rail) }}
                </div>
                <div class="col">
                    {{ wtf.form_field(form.date) }}
                </div>
            </div>

            <div class="row justify-content-center text-center align-items-center">
                <div class="col">
                    {{ wtf.form_field(form.submit_button, button_map={'submit_button': 'warning'}) }}
                </div>
            </div>
        </form>
        {% if graphJSONAverage3d %}
            <div>
                <div id="chart_av" style="height: 60%; width: 100%;"></div>
            </div>
            {#TODO: перреписать генерацию графиков можно просто передвать json и все будет гуд!#}
            <!-- Chart code -->
            <script>
                var grahp_av = {{ graphJSONAverage3d | safe}};
                create_plot_pred("chart_av", grahp_av,
                    "Предсказание для всех слоев металлолома",
                    "Классы металлолома",
                    "Процентное соотношение классов %",
                    "%"
                );
            </script>
        {% endif %}
    </div>
    <script charset="utf-8" type="text/javascript">

        $(function () {

            // jQuery selection for the 3 select boxes
            var dropdown = {
                number: $('#select_number'),
                sender_s: $('#select_sender'),
                rail: $('#select_rail'),
                date_s: $('#select_date'),

            };

            // call to update on load
            updateCounties();

            // function to call XHR and update county dropdown
            function updateCounties() {
                var send = {
                    number: dropdown.number.children('option:selected').text()
                };
                dropdown.sender_s.attr('disabled', 'disabled');
                dropdown.sender_s.empty();
                dropdown.rail.attr('disabled', 'disabled');
                dropdown.rail.empty();
        dropdown.date_s.attr('disabled', 'disabled');
        dropdown.date_s.empty();
        $.getJSON("{{ url_for('scrap._get_senders') }}", send, function(data) {
                data[0].forEach(function (elem) {
                    dropdown.sender_s.append(
                        $('<option>', {
                            value: elem[0],
                            text: elem[1]
                        })
                    );
                });
                 data[1].forEach(function (elem) {
                    dropdown.rail.append(
                        $('<option>', {
                            value: elem[0],
                            text: elem[1]
                        })
                    );
                });
                  data[2].forEach(function (elem) {
                    dropdown.date_s.append(
                        $('<option>', {
                            value: elem[0],
                            text: elem[1]
                        })
                    );
                });
            dropdown.sender_s.removeAttr('disabled');
            dropdown.rail.removeAttr('disabled');
            dropdown.date_s.removeAttr('disabled');
        });
    }

    // event listener to state dropdown change
    dropdown.number.on('change', function() {
        updateCounties();
    });

});

</script>

    <style>


        select[multiple] option:checked {
            background: #abaa1b -webkit-linear-gradient(bottom, #ab9000 0%, #ffb013 100%);
        }

        .radio {
            padding-left: 30px;
        }

        .sr-only {
            position: relative;
            width: auto;
            height: auto;
        }

    </style>
{% endblock %}

templates/scrap_template/segmentation_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center text-center" style="background: #373737;">
            <div class="col-sm-4 mt-4 mb-4">
                <img id="crop" src="{{ images[0][0] }}">
            </div>
            <div class="col-sm-3 justify-content-center text-center list-group m-4"
                 style="float:left; max-height: 250px; overflow: auto; display: inline-block">
                {% for image in images %}
                    <button type="button"
                            style="color: rgba(255, 255, 255, 0.4); background: #464646; outline-color: #646464;"
                            id={{ loop.index }} class="list-group-item mb-1 list-group-item-action">
                    {{ image[0].split('\\')[-1] }}
                    </button>
                {% endfor %}
            </div>
        </div>
        <div class=" row justify-content-center text-center mt-5">
            <div id="chart_one" class="column"></div>
            <div id="chart_av" class="column"></div>
        </div>


        {#TODO: перреписать генерацию графиков можно просто передвать json и все будет гуд!#}
        <!-- Chart code -->
        <script type="text/javascript">
            var grahp_av = {{ graphJSONAverage3d | safe}};
            create_plot_pred("chart_av", grahp_av,
                "Предсказание для всех слоев металлолома",
                "Классы металлолома",
                "Процентное соотношение классов %",
                "%"
            );

            var graphs3d = {{ graphJSON3d | safe }};
            var images_result = {{images | safe}};
            create_plot_pred("chart_one", graphs3d[0],
                "Предсказание для всех слоев металлолома",
                "Классы металлолома",
                "Процентное соотношение классов %",
                "%"
            );

            var id = 1
            $('#' + id).css('color', 'rgb(255,255,255,0.64)');
            $("button").click(function () {
                if (id !== this.id) {
                    $('#' + this.id).css("color", "rgb(255,255,255,0.64)")
                    $('#' + id).css('color', 'rgba(255, 255, 255, 0.4)');
                    id = this.id;
                }
                $("#crop").attr("src", images_result[this.id - 1][0]);
                create_plot_pred("chart_one", graphs3d[this.id - 1],
                    "Предсказание для одного слоя металлолома",
                    "Классы металлолома",
                    "Процентное соотношение классов %",
                    "%"
                );
            });
        </script>
    </div>

    <style>

        .column {
            float: left;
            width: 50%;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        #chart_one, #chart_av {
            height: 500px;
        }
    </style>
{% endblock %}

templates/scrap_template/submit_classification.html
{% extends "base.html" %}
{% block content %}
    <div class="container">

        {# содержимое приложения которое должно быть предоставлено в блоке app_content #}
        {% block app_content %}{% endblock %}
    </div>
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-8">
                {{ wtf.quick_form(form, button_map={'submit_button': 'warning'}) }}
            </div>
        </div>
    </div>

    <style>


        .help-block {
            color: red;
            display: none;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            font-size: 26px;
            margin-top: 4px;

        }

        .form-control {
            margin-left: 30px;
            background-color: rgba(21, 21, 21, 0.6) !important;
            height: calc(1.5em + .75rem + 30px);
            border-color: rgba(108, 108, 108, 0.6);
            color: rgba(255, 207, 36, 1) !important;
        }

        .form-control:focus {
            background-color: rgba(21, 21, 21, 0.6) !important;
            box-shadow: inset 0 1px 1px rgba(255, 207, 36, 1), 0 0 8px rgba(255, 207, 36, 1);
            border-color: rgba(255, 207, 36, 0.7);
            color: rgba(255, 207, 36, 1) !important;
        }

        /* Chrome, Safari, Edge, Opera */
        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        /* Firefox */
        input[type=number] {
            -moz-appearance: textfield;
        }

        input[type="number"]:required {
            background-color: rgba(21, 21, 21, 0.6) !important;
            border-color: rgba(108, 108, 108, 0.6) !important;
        }

        #submit_button {
            margin-top: 10px;
            width: 300px;
            height: 70px;
        }

        .control-label {
            font-family: PF Bague Sans Pro;
            font-style: normal;
            font-weight: normal;
            /* identical to box height */

            color: #7A7A7A;
            font-size: 24px;
            display: inherit;
            float: left;
        }
    </style>
{% endblock %}